#!/bin/bash

PROJROOT=/opt/genoome;
VENVPATH=/home/ubuntu/.pyenv/versions/venv;
PYPATH=$VENVPATH/bin/python;
GULPPATH=$VENVPATH/bin/gulp;

source $VENVPATH/bin/activate;
cd $PROJROOT/genoome/genoome/ && sudo git checkout -- . && \
git pull origin master && \
pip instal -r ../requirements/production.txt \
cd ../ && \
npm install && \
./node_modules/.bin/bower install && \
cd - && \
$GULPPATH --gulpfile ../gulpfile.js --cwd ../ dist && \
$PYPATH ./manage.py migrate
$PYPATH ./manage.py collectstatic --noinput --settings=genoome.settings.production && \
sudo touch /etc/uwsgi/vassals/genoome.ini && \
sudo chown -R ubuntu:www-data $PROJROOT/genoome/genoome/assets/;

echo 'Success';
